name: mysql-standard
version: 0.0.1
id: 632eb401-434c-436d-8525-3202ce9df329
description: "MySQL by Helm Broker."
displayName: "mysql-standard"

tags: database
labels:
  experimental: "true"
providerDisplayName: helm
longDescription: "MySQL by Helm Broker."
documentationURL: https://hub.docker.com/_/mysql/
supportURL: https://hub.docker.com/_/mysql/
bindable: true
bindingsRetrievable: true