name: mysql
version: 0.0.1
id: 332588e0-6c2c-4f56-a6af-a56fd01ec4b4
description: "MySQL by Helm Broker."
displayName: "mysql"

tags: database
labels:
  experimental: "true"
providerDisplayName: helm
longDescription: "MySQL by Helm Broker."
documentationURL: https://hub.docker.com/_/mysql/
supportURL: https://hub.docker.com/_/mysql/
bindable: true
bindingsRetrievable: true