name: rabbitmq
version: 1.1.0
id: 6530fae8-fb86-450b-8ab3-3ca5fb6c77d0
description: "rabbitmq."
displayName: "rabbitmq"

tags: mq
labels:
  experimental: "true"
providerDisplayName: bitnami
longDescription: "This is rabbitmq addon just to show how to expose services using Kyma helm-broker"
documentationURL: https://github.com/bitnami/bitnami-docker-rabbitmq
supportURL: https://www.rabbitmq.com
bindable: true
bindingsRetrievable: true
